# Generated by Django 3.2.7 on 2021-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=15)),
                ('last', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=11)),
                ('created', models.DateField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lastvisit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
