# Generated by Django 3.2.7 on 2021-09-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='phone',
        ),
    ]
