# Generated by Django 3.2.7 on 2021-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
