# Generated by Django 3.2.7 on 2021-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_employee_creations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
