# Generated by Django 3.2.7 on 2021-10-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
