# Generated by Django 3.2.7 on 2021-09-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0006_alter_employee_creations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_period', models.IntegerField()),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_marketed', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rewards.customer')),
            ],
        ),
    ]
