# Generated by Django 3.2.7 on 2021-09-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_employee_creations'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagingCustomer',
            new_name='MCustomer',
        ),
    ]
