# Generated by Django 3.2.7 on 2021-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_messagingcustomer_mcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcustomer',
            name='last_marketed',
            field=models.DateTimeField(),
        ),
    ]
