# Generated by Django 3.2.7 on 2021-09-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_mcustomer_last_marketed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('reachpercent', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('reachtotal', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
