# Generated by Django 3.2.7 on 2021-09-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='comments',
            field=models.CharField(default='ggggg', max_length=20),
            preserve_default=False,
        ),
    ]
