# Generated by Django 3.2.7 on 2021-09-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_behavior_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='reachtotal',
            field=models.IntegerField(null=True),
        ),
    ]
