# Generated by Django 3.2.7 on 2021-09-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_behavior_reachtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.behavior')),
            ],
        ),
    ]
