# Generated by Django 3.2.7 on 2021-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='demo',
            field=models.CharField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
