# Generated by Django 3.2.7 on 2021-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_behavior_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behavior',
            old_name='reachpercent',
            new_name='reach_percent',
        ),
        migrations.RenameField(
            model_name='behavior',
            old_name='reachtotal',
            new_name='reach_total',
        ),
        migrations.AlterField(
            model_name='behavior',
            name='demo',
            field=models.CharField(choices=[(1, 'Lower Percentile Customers'), (2, 'Middle Percentile Customers'), (3, 'Higher Percentile Customers'), (4, 'Random'), (5, 'Long Time No See'), (6, 'Recently Visited')], max_length=2),
        ),
    ]
