# Generated by Django 3.2.7 on 2021-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20210923_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='reached',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='demo',
            field=models.CharField(choices=[('1', 'Lower Percentile Customers'), ('2', 'Middle Percentile Customers'), ('3', 'Higher Percentile Customers'), ('4', 'Random'), ('5', 'Long Time No See'), ('6', 'Recently Visited')], max_length=2),
        ),
    ]
