# Generated by Django 3.2.7 on 2021-09-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_auto_20210923_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='reached',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
