# Generated by Django 3.2.7 on 2021-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_alter_behavior_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='platform',
            field=models.CharField(choices=[('1', 'Email'), ('2', 'Phone')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
