# Generated by Django 3.2.7 on 2021-09-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_behavior_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='platform',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=6),
        ),
    ]
