# Generated by Django 3.2.7 on 2021-09-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_alter_behavior_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='platform',
            field=models.CharField(choices=[('1', 'Email'), ('2', 'Phone')], max_length=6),
        ),
    ]
