# Generated by Django 3.2.7 on 2021-09-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_alter_behavior_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='comments',
            field=models.CharField(max_length=100),
        ),
    ]
