# Generated by Django 3.2.7 on 2021-10-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_alter_behavior_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcustomer',
            name='opted',
            field=models.BooleanField(default=False),
        ),
    ]
