# Generated by Django 3.2.7 on 2021-10-06 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_employee_creations'),
        ('messaging', '0017_mcustomer_opted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.CharField(max_length=100)),
                ('opt', models.CharField(max_length=100, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rewards.customer')),
            ],
        ),
    ]
