# Generated by Django 3.2.7 on 2021-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_optrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optrecord',
            name='opt',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
