# Generated by Django 3.2.7 on 2021-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_alter_optrecord_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optrecord',
            name='opt',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
