# Generated by Django 3.2.7 on 2021-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0020_alter_optrecord_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
