# Generated by Django 3.2.7 on 2021-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0021_behavior_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='reach_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
            preserve_default=False,
        ),
    ]
