# Generated by Django 3.2.7 on 2021-10-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0022_alter_behavior_reach_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='reached',
            field=models.IntegerField(null=True),
        ),
    ]
