# Generated by Django 3.2.7 on 2021-10-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0023_alter_behavior_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='reached',
            field=models.IntegerField(default=0),
        ),
    ]
