# Generated by Django 3.2.7 on 2021-10-19 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0024_alter_behavior_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavior',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 3, 33, 16, 320466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
