# Generated by Django 3.2.7 on 2021-10-19 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0027_alter_behavior_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 3, 33, 48, 907267, tzinfo=utc)),
        ),
    ]
