# Generated by Django 3.2.7 on 2021-10-19 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0028_alter_behavior_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 16, 59, 7, 697495, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='attachments/')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.behavior')),
            ],
        ),
    ]
