# Generated by Django 3.2.7 on 2021-10-19 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0031_auto_20211019_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 17, 36, 49, 820970, tzinfo=utc)),
        ),
    ]
