# Generated by Django 3.2.7 on 2021-10-19 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0034_alter_behavior_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 23, 19, 25, 473542, tzinfo=utc)),
        ),
    ]
