# Generated by Django 3.2.7 on 2021-10-20 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0035_auto_20211019_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 2, 4, 12, 94765, tzinfo=utc)),
        ),
    ]
