# Generated by Django 3.2.7 on 2021-10-20 03:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_alter_customer_phone'),
        ('messaging', '0036_auto_20211020_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 3, 5, 26, 363257, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.attachment')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.behavior')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.customer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.message')),
            ],
        ),
    ]
