# Generated by Django 3.2.7 on 2021-10-20 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0037_auto_20211020_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 3, 5, 33, 495622, tzinfo=utc)),
        ),
    ]
