# Generated by Django 3.2.7 on 2021-10-26 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0041_alter_behavior_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 3, 29, 8, 338481, tzinfo=utc)),
        ),
    ]
