# Generated by Django 3.2.7 on 2021-10-29 03:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0042_alter_behavior_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 3, 23, 11, 696193, tzinfo=utc)),
        ),
    ]
