# Generated by Django 2.1.15 on 2021-10-30 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0044_auto_20211030_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 15, 26, 3, 754808, tzinfo=utc)),
        ),
    ]
