# Generated by Django 2.1.15 on 2021-10-31 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0045_auto_20211030_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 23, 42, 36, 16374, tzinfo=utc)),
        ),
    ]
