# Generated by Django 2.1.15 on 2021-11-11 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0046_auto_20211031_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 0, 58, 47, 464564, tzinfo=utc)),
        ),
    ]
