# Generated by Django 2.1.15 on 2021-11-11 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_auto_20211030_0453'),
        ('messaging', '0047_auto_20211111_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Attachment')),
            ],
        ),
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 0, 59, 1, 427138, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='shortmessage',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Behavior'),
        ),
        migrations.AddField(
            model_name='shortmessage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.Customer'),
        ),
        migrations.AddField(
            model_name='shortmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message'),
        ),
    ]
