# Generated by Django 2.1.15 on 2021-11-12 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0048_auto_20211111_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortmessage',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 3, 56, 13, 594819, tzinfo=utc)),
        ),
    ]
