# Generated by Django 2.1.15 on 2021-11-13 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0050_auto_20211112_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 4, 43, 0, 286076, tzinfo=utc)),
        ),
    ]
