# Generated by Django 2.1.15 on 2021-11-17 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0051_auto_20211113_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 2, 14, 16, 43708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shortmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
