# Generated by Django 2.1.15 on 2021-11-19 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0056_auto_20211119_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 2, 52, 28, 224187, tzinfo=utc)),
        ),
    ]
