# Generated by Django 2.1.15 on 2021-11-22 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0058_auto_20211119_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 17, 20, 9, 795983, tzinfo=utc)),
        ),
    ]
