# Generated by Django 2.1.15 on 2021-11-22 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0060_auto_20211122_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 17, 22, 41, 273549, tzinfo=utc)),
        ),
    ]
